/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularioInicial;

import BD.BD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Empresa extends javax.swing.JFrame {

    /**
     * Creates new form Empresa
     */
    public Empresa() {
        Variaveis.clickouPesquisa = 0;
        initComponents();
        fecharJanela();
        
        Icon lupa = new ImageIcon(getClass().getResource("lupa.gif"));
        pesquisar.setIcon(lupa);
        btnAtt.setVisible(false);
        if(Variaveis.conCad == 1){
            btnCad.setText("Cadastrar");
            idEmpresa.disable();
        }else{
            btnCad.setText("Consultar");
            CNPJ.disable();
            nome.disable();
            endereco.disable();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCad = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CNPJ = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        idEmpresa = new javax.swing.JTextField();
        pesquisar = new javax.swing.JLabel();
        btnAtt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Empresa");

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel2.setText("id Empresa");

        jLabel3.setText("CNPJ");

        jLabel4.setText("Nome");

        jLabel5.setText("Endereco");

        idEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idEmpresaFocusLost(evt);
            }
        });

        pesquisar.setText("...");
        pesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pesquisarMouseExited(evt);
            }
        });

        btnAtt.setText("Atualizar");
        btnAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCad)
                        .addGap(26, 26, 26)
                        .addComponent(btnAtt)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisar))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCad)
                    .addComponent(btnSair)
                    .addComponent(btnAtt))
                .addGap(41, 41, 41))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        // TODO add your handling code here:
        BD acessoUm = new BD();
        if(Variaveis.conCad == 1){
            if(CNPJ.getText().equals("") || nome.getText().equals("")|| endereco.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            } else {
                acessoUm.cadastrarEmpresa(CNPJ.getText(), nome.getText(), endereco.getText());
                JOptionPane.showMessageDialog(null, "Cadastrado");
                this.dispose();
                new MenuOpcoes().setVisible(true);
            }
        }else {
            if(idEmpresa.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha o campo de ID");
            }else{
            acessoUm.consultarEmpresa(Integer.parseInt(idEmpresa.getText()));
            CNPJ.setText(Variaveis.CPNJ);
            nome.setText(Variaveis.NomeEmpresa);
            endereco.setText(Variaveis.EnderecoEmpresa);        
            }
        }
    }//GEN-LAST:event_btnCadActionPerformed

    private void fecharJanela(){
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
    }
        private void exitForm(java.awt.event.WindowEvent evt) {
        //Variaveis.voltar = 0;
        //Variaveis.fechar = 0;
        //new ConfirmarSaida().setVisible(true);
        int aux = Funcoes.voltar("Deseja voltar ao menu de opções?","SIM","NÃO");
        if (aux == 1){
            new MenuOpcoes().setVisible(true);
            this.dispose();
        }        
    }
        
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        /*Variaveis.voltar = 1;
        Variaveis.fechar = 1;
        new ConfirmarSaida().setVisible(true);
        if(Variaveis.cancelar == 1){
            new MenuOpcoes().setVisible(true);
            this.dispose();
        }*/
        int aux = Funcoes.voltar("Deseja voltar ao menu de opções?","SIM","NÃO");
        if (aux == 1){
            new MenuOpcoes().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        if(Variaveis.clickouPesquisa == 1){
            idEmpresa.setText(Variaveis.idEmpresaPesquisa);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void pesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarMouseClicked
        // TODO add your handling code here:
        Variaveis.exame = 1;
        new PesquisarEmpresa().setVisible(true);
    }//GEN-LAST:event_pesquisarMouseClicked

    private void pesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarMouseEntered
        // TODO add your handling code here:
        Icon lupaSelecionada = new ImageIcon(getClass().getResource("lupaselecionada.gif"));
        pesquisar.setIcon(lupaSelecionada);
    }//GEN-LAST:event_pesquisarMouseEntered

    private void pesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarMouseExited
        // TODO add your handling code here:
        Icon lupa = new ImageIcon(getClass().getResource("lupa.gif"));

        pesquisar.setIcon(lupa);
    }//GEN-LAST:event_pesquisarMouseExited

    private void idEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idEmpresaFocusLost
        // TODO add your handling code here:
        if(!idEmpresa.getText().equals("")){        
                BD acessoUm = new BD();
                acessoUm.consultarEmpresa(Integer.parseInt(idEmpresa.getText()));
                nome.setText(Variaveis.NomeEmpresa);
                CNPJ.setText(Variaveis.CPNJ);
                endereco.setText(Variaveis.EnderecoEmpresa);
                
                int aux = Funcoes.voltar("Deseja atualizar o cadastro?","SIM", "NÃO");
                if(aux == 1){
                    nome.setEnabled(true);
                    CNPJ.setEnabled(true);
                    endereco.setEnabled(true);
                    btnAtt.setVisible(true);
                }}
    }//GEN-LAST:event_idEmpresaFocusLost

    private void btnAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttActionPerformed
        try {
            // TODO add your handling code here:
            BD con = new BD();
            Connection c = con.conectar();
            
            PreparedStatement pesquisarStmt = c.prepareStatement("UPDATE empresa set CNPJ = ?, nome = ?, endereco = ? WHERE idEmpresa = ?");
            
            pesquisarStmt.setString(1, CNPJ.getText());
            pesquisarStmt.setString(2, nome.getText());
            pesquisarStmt.setString(3, endereco.getText());
            pesquisarStmt.setInt(4, Integer.parseInt(idEmpresa.getText()));
            pesquisarStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Atualizado");
        } catch (SQLException ex) {
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_btnAttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNPJ;
    private javax.swing.JButton btnAtt;
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnSair;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField idEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel pesquisar;
    // End of variables declaration//GEN-END:variables
}
