/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularioInicial;

import BD.BD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import  javax.swing.ImageIcon;

/**
 *
 * @author andre
 */
public class MenuOpcoes extends javax.swing.JFrame {

    /**
     * Creates new form MenuOpcoes
     */
    public MenuOpcoes() {
        initComponents();
        fecharJanela();
        Icon anamnese = new ImageIcon(getClass().getResource("anamnese.gif"));
        Icon paciente = new ImageIcon(getClass().getResource("paciente.gif"));
        Icon empresa = new ImageIcon(getClass().getResource("empresa.gif"));
        Icon aso = new ImageIcon(getClass().getResource("exameAso.gif"));
        Icon editar = new ImageIcon(getClass().getResource("editar-arquivo.png"));
        Icon pesquisaPaciente = new ImageIcon(getClass().getResource("pesquisaPaciente.png"));
        Icon pesquisaEmpresa = new ImageIcon(getClass().getResource("pesquisaEmpresa.png"));
        Icon impressora = new ImageIcon(getClass().getResource("impressora.png"));
        btnCadAn.setIcon(anamnese);
        btnConAn.setIcon(editar);
        btnImprimir.setIcon(impressora);
        cadPaciente.setIcon(paciente);
        cadEmpr.setIcon(empresa);
        conPaciente.setIcon(editar);
        conEmpresa.setIcon(editar);
        pesqPac.setIcon(pesquisaPaciente);
        pesqEmp.setIcon(pesquisaEmpresa);
        btnImprimirAso.setIcon(impressora);
        btnCadAso.setIcon(aso);
        btnConAso.setIcon(editar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        painelImagemFundo1 = new formularioInicial.PainelImagemFundo();
        cadPaciente = new javax.swing.JButton();
        conPaciente = new javax.swing.JButton();
        pesqPac = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        painelImagemFundo2 = new formularioInicial.PainelImagemFundo();
        cadEmpr = new javax.swing.JButton();
        conEmpresa = new javax.swing.JButton();
        pesqEmp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        painelImagemFundo3 = new formularioInicial.PainelImagemFundo();
        btnCadAn = new javax.swing.JButton();
        btnConAn = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        painelImagemFundo4 = new formularioInicial.PainelImagemFundo();
        btnCadAso = new javax.swing.JButton();
        btnConAso = new javax.swing.JButton();
        btnImprimirAso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(java.awt.Color.lightGray);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Menu de Opções");

        painelImagemFundo1.setImg(new ImageIcon("src/formularioInicial/ImagemClinica.png"));

        cadPaciente.setText("Cadastrar");
        cadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPacienteActionPerformed(evt);
            }
        });

        conPaciente.setText("Editar");
        conPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conPacienteActionPerformed(evt);
            }
        });

        pesqPac.setText("Pesquisar");
        pesqPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqPacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelImagemFundo1Layout = new javax.swing.GroupLayout(painelImagemFundo1);
        painelImagemFundo1.setLayout(painelImagemFundo1Layout);
        painelImagemFundo1Layout.setHorizontalGroup(
            painelImagemFundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImagemFundo1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(painelImagemFundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesqPac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        painelImagemFundo1Layout.setVerticalGroup(
            painelImagemFundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImagemFundo1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(cadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(conPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(pesqPac, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagemFundo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagemFundo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Paciente", jPanel1);

        painelImagemFundo2.setImg(new ImageIcon("src/formularioInicial/ImagemClinica.png"));

        cadEmpr.setText("Cadastrar");
        cadEmpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadEmprActionPerformed(evt);
            }
        });

        conEmpresa.setText("Editar");
        conEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conEmpresaActionPerformed(evt);
            }
        });

        pesqEmp.setText("Pesquisar");
        pesqEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelImagemFundo2Layout = new javax.swing.GroupLayout(painelImagemFundo2);
        painelImagemFundo2.setLayout(painelImagemFundo2Layout);
        painelImagemFundo2Layout.setHorizontalGroup(
            painelImagemFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImagemFundo2Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(painelImagemFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesqEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadEmpr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        painelImagemFundo2Layout.setVerticalGroup(
            painelImagemFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImagemFundo2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(cadEmpr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(conEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(pesqEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagemFundo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(painelImagemFundo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empresas", jPanel2);

        painelImagemFundo3.setImg(new ImageIcon("src/formularioInicial/ImagemClinica.png"));

        btnCadAn.setText("Cadastrar");
        btnCadAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAnActionPerformed(evt);
            }
        });

        btnConAn.setText("Editar");
        btnConAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConAnActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelImagemFundo3Layout = new javax.swing.GroupLayout(painelImagemFundo3);
        painelImagemFundo3.setLayout(painelImagemFundo3Layout);
        painelImagemFundo3Layout.setHorizontalGroup(
            painelImagemFundo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImagemFundo3Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(painelImagemFundo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConAn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadAn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(197, 197, 197))
        );
        painelImagemFundo3Layout.setVerticalGroup(
            painelImagemFundo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImagemFundo3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnCadAn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnConAn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagemFundo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(painelImagemFundo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Anamnese", jPanel3);

        painelImagemFundo4.setImg(new ImageIcon("src/formularioInicial/ImagemClinica.png"));

        btnCadAso.setText("Cadastrar");
        btnCadAso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAsoActionPerformed(evt);
            }
        });

        btnConAso.setText("Editar");
        btnConAso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConAsoActionPerformed(evt);
            }
        });

        btnImprimirAso.setText("Imprimir");
        btnImprimirAso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirAsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelImagemFundo4Layout = new javax.swing.GroupLayout(painelImagemFundo4);
        painelImagemFundo4.setLayout(painelImagemFundo4Layout);
        painelImagemFundo4Layout.setHorizontalGroup(
            painelImagemFundo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImagemFundo4Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(painelImagemFundo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadAso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConAso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimirAso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(197, 197, 197))
        );
        painelImagemFundo4Layout.setVerticalGroup(
            painelImagemFundo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImagemFundo4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnCadAso, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnConAso, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnImprimirAso, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagemFundo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagemFundo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Atestado de Saúde Ocupacional", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void fecharJanela(){
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
    }
        private void exitForm(java.awt.event.WindowEvent evt) {
        //Variaveis.fechar = 0;
        //Variaveis.voltar = 0;
        //new ConfirmarSaida().setVisible(true);
        Funcoes.sair();
    }
        
    private void cadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPacienteActionPerformed
        // TODO add your handling code here:
        Variaveis.conCad = 1;
        Variaveis.cancelar = 0;
        Paciente paciente = new Paciente();
        paciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadPacienteActionPerformed

    private void cadEmprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadEmprActionPerformed
        // TODO add your handling code here:
        Variaveis.conCad = 1;
        Variaveis.cancelar = 0;
        new Empresa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadEmprActionPerformed

    private void conPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conPacienteActionPerformed
        // TODO add your handling code here:
        Variaveis.conCad = 0;
        Variaveis.cancelar = 0;
        Paciente paciente = new Paciente();
        paciente.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_conPacienteActionPerformed

    private void conEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conEmpresaActionPerformed
        // TODO add your handling code here:
        Variaveis.conCad = 0;
        Variaveis.cancelar = 0;
        new Empresa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_conEmpresaActionPerformed

    private void pesqPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqPacActionPerformed
        // TODO add your handling code here:
        Variaveis.pesqPac = 0;
        new PesquisarPaciente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pesqPacActionPerformed

    private void pesqEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqEmpActionPerformed
        // TODO add your handling code here:
        Variaveis.pesqEmp = 0;
        new PesquisarEmpresa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pesqEmpActionPerformed

    private void btnCadAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAnActionPerformed
        // TODO add your handling code here:
        Variaveis.cadConExame = 1;
        new Exame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadAnActionPerformed

    private void btnConAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConAnActionPerformed
        // TODO add your handling code here:
        Variaveis.cadConExame = 0;
        new Exame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConAnActionPerformed
    BD con = new BD();
    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        int aux = Integer.parseInt(JOptionPane.showInputDialog(null,"Digite o id da Anamnese"));
        //int aux = 1;
        Connection c = con.conectar();
        
        String src = "Exame.jasper";
        
        JasperPrint jasperPrint = null;
        try{
            HashMap params = new HashMap<>();
            
            params.put("idAnamnese",aux);
            jasperPrint = JasperFillManager.fillReport(src, params , c); 
        } catch (JRException ex){
            System.out.println("Error: "+ ex);
        }
        
        JasperViewer view = new JasperViewer(jasperPrint, false);
        
        view.setVisible(true);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnCadAsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAsoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        Variaveis.cadConExame = 1;
        new aso().setVisible(true);
    }//GEN-LAST:event_btnCadAsoActionPerformed

    private void btnImprimirAsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirAsoActionPerformed
        // TODO add your handling code here:
        int aux = Integer.parseInt(JOptionPane.showInputDialog(null,"Digite o id da ASO"));
        //int aux = 1;
        
        
        Connection c = con.conectar();
        
        String src = "ASO.jasper";
        
        JasperPrint jasperPrint = null;
        try{
            HashMap params = new HashMap<>();
            
            params.put("idAso",aux);
            jasperPrint = JasperFillManager.fillReport(src, params , c); 
        } catch (JRException ex){
            System.out.println("Error: "+ ex);
        }
        
        JasperViewer view = new JasperViewer(jasperPrint, false);
        
        view.setVisible(true);
        
    }//GEN-LAST:event_btnImprimirAsoActionPerformed

    private void btnConAsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConAsoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Variaveis.cadConExame = 0;
        new aso().setVisible(true);
        
        
        
    }//GEN-LAST:event_btnConAsoActionPerformed

    
    
    /*
    public void imprimirRelatorio() throws JRException{
        int aux = Integer.parseInt(JOptionPane.showInputDialog(null,"Digite o id da Anamnese"));
        
        Connection c = con.conectar();
        
        String src = "Exame.jasper";
        
        JasperPrint jasperPrint = null;
        try{
            HashMap params = new HashMap<>();
            
            params.put("ID da anamnese",aux);
            jasperPrint = JasperFillManager.fillReport(src, params , c); 
        } catch (JRException ex){
            System.out.println("Error: "+ ex);
        }
        
        JasperViewer view = new JasperViewer(jasperPrint, false);
        
        view.setVisible(true);
    }
    */
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadAn;
    private javax.swing.JButton btnCadAso;
    private javax.swing.JButton btnConAn;
    private javax.swing.JButton btnConAso;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnImprimirAso;
    private javax.swing.JButton cadEmpr;
    private javax.swing.JButton cadPaciente;
    private javax.swing.JButton conEmpresa;
    private javax.swing.JButton conPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private formularioInicial.PainelImagemFundo painelImagemFundo1;
    private formularioInicial.PainelImagemFundo painelImagemFundo2;
    private formularioInicial.PainelImagemFundo painelImagemFundo3;
    private formularioInicial.PainelImagemFundo painelImagemFundo4;
    private javax.swing.JButton pesqEmp;
    private javax.swing.JButton pesqPac;
    // End of variables declaration//GEN-END:variables
}
