/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularioInicial;

import BD.BD;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Paciente extends javax.swing.JFrame {

    /**
     * Creates new form Paciente
     */
    public Paciente() {
        initComponents();
        Variaveis.clickouPesquisa = 0;
        fecharJanela();
        Icon lupa = new ImageIcon(getClass().getResource("lupa.gif"));
        pesquisar.setIcon(lupa);
        atualizar.setVisible(false);
        if(Variaveis.conCad == 1){
            btnCad.setText("Cadastrar");
            idPaciente.disable();
            pesquisar.setVisible(false);
            
        }else{
            btnCad.setText("Consultar");
            pesquisar.setVisible(true);
            nome.disable();
            data.disable();
            cor.disable();
            estadoCivil.disable();
            RG.disable();
            Endereco.disable();
            Cidade.disable();
            Cargo.disable();
            idEmpresa.disable();
            pai.disable();
            mae.disable();
            naturalidade.disable();
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCad = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        idPaciente = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        data = new javax.swing.JTextField();
        cor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        estadoCivil = new javax.swing.JTextField();
        RG = new javax.swing.JTextField();
        Endereco = new javax.swing.JTextField();
        Cidade = new javax.swing.JTextField();
        Cargo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idEmpresa = new javax.swing.JTextField();
        atualizar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        pai = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        mae = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        naturalidade = new javax.swing.JTextField();
        sexoM = new javax.swing.JRadioButton();
        sexoF = new javax.swing.JRadioButton();
        pesquisar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(java.awt.Color.lightGray);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Paciente");

        jLabel2.setText("idPaciente");

        jLabel3.setText("Nome");

        jLabel4.setText("Data Nascimento");

        jLabel5.setText("Sexo");

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        btnSair.setText("Cancelar");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel6.setText("Cor");

        idPaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idPacienteFocusLost(evt);
            }
        });

        jLabel7.setText("Estado Civil");

        jLabel8.setText("RG");

        jLabel9.setText("Endereço");

        jLabel10.setText("Cidade");

        jLabel11.setText("Cargo");

        jLabel12.setText("idEmpresa");

        atualizar.setText("Atualizar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        jLabel13.setText("Pai");

        jLabel14.setText("Mâe");

        jLabel15.setText("Naturalidade");

        buttonGroup1.add(sexoM);
        sexoM.setText("M");

        buttonGroup1.add(sexoF);
        sexoF.setText("F");

        pesquisar.setText("...");
        pesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pesquisarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCad)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(85, 85, 85)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(idEmpresa)
                                    .addComponent(idPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(data, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pai, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(sexoM)
                                        .addGap(18, 18, 18)
                                        .addComponent(sexoF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(atualizar)
                                        .addGap(113, 113, 113))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(pesquisar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel14))
                                        .addGap(70, 70, 70)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(naturalidade)
                                    .addComponent(RG)
                                    .addComponent(estadoCivil)
                                    .addComponent(Cargo, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(mae)
                                    .addComponent(Cidade)
                                    .addComponent(Endereco)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSair)))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(sexoM)
                    .addComponent(sexoF)
                    .addComponent(Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(mae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(naturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCad)
                    .addComponent(btnSair)
                    .addComponent(atualizar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        /*Variaveis.voltar = 1;
        Variaveis.fechar = 1;
        new ConfirmarSaida().setVisible(true);
        if(Variaveis.cancelar == 1){
            new MenuOpcoes().setVisible(true);
            this.dispose();
        }*/
        int aux = Funcoes.voltar("Deseja voltar ao menu de opções?", "SIM", "NÃO");
        if (aux == 1){
            new MenuOpcoes().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        // TODO add your handling code here:
        BD acessoUm = new BD();
        String sexo = "";
        if(sexoM.isSelected()){
            sexo = "M";
        }else{
            sexo = "F";
        }
        if(Variaveis.conCad == 1){
            if(nome.getText().equals("") || data.getText().equals("")|| sexo.equals("")|| cor.getText().equals("")|| estadoCivil.getText().equals("")|| RG.getText().equals("")|| Endereco.getText().equals("")|| Cidade.getText().equals("")|| Cargo.getText().equals("")||idEmpresa.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            } else {
                acessoUm.cadastrarPaciente(nome.getText(), data.getText(), sexo, cor.getText(), estadoCivil.getText(), RG.getText(), Endereco.getText(), Cidade.getText(), Cargo.getText(), pai.getText(), mae.getText(), naturalidade.getText(), Integer.parseInt(idEmpresa.getText()));
                JOptionPane.showMessageDialog(null, "Cadastrado");
                this.dispose();
                new MenuOpcoes().setVisible(true);
            }
        } else {
            if(idPaciente.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha o campo de ID");
            }else{
                acessoUm.consultarPaciente(Integer.parseInt(idPaciente.getText()));
                Cargo.setText(Variaveis.Cargo);
                Cidade.setText(Variaveis.Cidade);
                Endereco.setText(Variaveis.Endereco);
                RG.setText(Variaveis.RG);
                cor.setText(Variaveis.cor);
                data.setText(Variaveis.data);
                estadoCivil.setText(Variaveis.estadoCivil);
                idEmpresa.setText(Variaveis.idEmpresa);
                nome.setText(Variaveis.nome);
                if(Variaveis.sexo.equals("M")){
                    sexoM.setSelected(true);
                    
                }else{
                    sexoF.setSelected(true);
                }
                pai.setText(Variaveis.pai);
                mae.setText(Variaveis.mae);
                naturalidade.setText(Variaveis.naturalidade);
                int aux = Funcoes.voltar("Deseja atualizar o cadastro?","SIM", "NÃO");
                if(aux == 1){
                    idPaciente.disable();
                    nome.setEnabled(true);
                    data.setEnabled(true);
                    cor.setEnabled(true);
                    estadoCivil.setEnabled(true);
                    RG.setEnabled(true);
                    Endereco.setEnabled(true);
                    Cidade.setEnabled(true);
                    Cargo.setEnabled(true);
                    idEmpresa.setEnabled(true);
                    pai.setEnabled(true);
                    mae.setEnabled(true);
                    atualizar.setVisible(true);
                    btnCad.setVisible(false);
                    naturalidade.setVisible(true);
                }
                
            }
        }
    }//GEN-LAST:event_btnCadActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        BD acessoUm = new BD();
        String sexo = "";
        if(sexoM.isSelected()){
            sexo = "M";
        }else{
            sexo = "F";
        }
        acessoUm.attPaciente(nome.getText(), data.getText(), sexo, cor.getText(), estadoCivil.getText(), RG.getText(), Endereco.getText(), Cidade.getText(), Cargo.getText(), pai.getText(), mae.getText(), naturalidade.getText(), Integer.parseInt(idEmpresa.getText()), Integer.parseInt(idPaciente.getText()));
        JOptionPane.showMessageDialog(null, "Atualizado");
        atualizar.setVisible(false);
        btnCad.setText("Consultar");
        btnCad.setVisible(true);
        idPaciente.setEnabled(true);
        nome.disable();
        data.disable();
        cor.disable();
        estadoCivil.disable();
        RG.disable();
        Endereco.disable();
        Cidade.disable();
        Cargo.disable();
        idEmpresa.disable();
        pai.disable();
        mae.disable();
        naturalidade.disable();
    }//GEN-LAST:event_atualizarActionPerformed

    private void pesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarMouseEntered
        // TODO add your handling code here:
        Icon lupaSelecionada = new ImageIcon(getClass().getResource("lupaselecionada.gif"));
        pesquisar.setIcon(lupaSelecionada);
    }//GEN-LAST:event_pesquisarMouseEntered

    private void pesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarMouseExited
        // TODO add your handling code here:
        Icon lupa = new ImageIcon(getClass().getResource("lupa.gif"));
        
        pesquisar.setIcon(lupa);
    }//GEN-LAST:event_pesquisarMouseExited

    private void pesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarMouseClicked
        // TODO add your handling code here:
        Variaveis.exame = 1;
        new PesquisarPaciente().setVisible(true);
    }//GEN-LAST:event_pesquisarMouseClicked

    private void idPacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idPacienteFocusLost
        // TODO add your handling code here:
        if(!idPaciente.getText().equals("")){        
                BD acessoUm = new BD();
                acessoUm.consultarPaciente(Integer.parseInt(idPaciente.getText()));
                Cargo.setText(Variaveis.Cargo);
                Cidade.setText(Variaveis.Cidade);
                Endereco.setText(Variaveis.Endereco);
                RG.setText(Variaveis.RG);
                cor.setText(Variaveis.cor);
                data.setText(Variaveis.data);
                estadoCivil.setText(Variaveis.estadoCivil);
                idEmpresa.setText(Variaveis.idEmpresa);
                nome.setText(Variaveis.nome);
                if(Variaveis.sexo.equals("M")){
                    sexoM.setSelected(true);
                    
                }else{
                    sexoF.setSelected(true);
                }
                pai.setText(Variaveis.pai);
                mae.setText(Variaveis.mae);
                naturalidade.setText(Variaveis.naturalidade);
                int aux = Funcoes.voltar("Deseja atualizar o cadastro?","SIM", "NÃO");
                if(aux == 1){
                    idPaciente.disable();
                    nome.setEnabled(true);
                    data.setEnabled(true);
                    cor.setEnabled(true);
                    estadoCivil.setEnabled(true);
                    RG.setEnabled(true);
                    Endereco.setEnabled(true);
                    Cidade.setEnabled(true);
                    Cargo.setEnabled(true);
                    idEmpresa.setEnabled(true);
                    pai.setEnabled(true);
                    mae.setEnabled(true);
                    atualizar.setVisible(true);
                    btnCad.setVisible(false);
                    naturalidade.setEnabled(true);
                }}
    }//GEN-LAST:event_idPacienteFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        if(Variaveis.clickouPesquisa == 1){
            idPaciente.setText(Variaveis.idPacientePesquisa);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    
    private void fecharJanela(){
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
    }
        private void exitForm(java.awt.event.WindowEvent evt) {
        //Variaveis.voltar = 0;
        //Variaveis.fechar = 0;
        //new ConfirmarSaida().setVisible(true);
        int aux = Funcoes.voltar("Deseja voltar ao menu de opções?","SIM","NÃO");
        if (aux == 1){
            new MenuOpcoes().setVisible(true);
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cargo;
    private javax.swing.JTextField Cidade;
    private javax.swing.JTextField Endereco;
    private javax.swing.JTextField RG;
    private javax.swing.JButton atualizar;
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cor;
    private javax.swing.JTextField data;
    private javax.swing.JTextField estadoCivil;
    private javax.swing.JTextField idEmpresa;
    private javax.swing.JTextField idPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mae;
    private javax.swing.JTextField naturalidade;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField pai;
    private javax.swing.JLabel pesquisar;
    private javax.swing.JRadioButton sexoF;
    private javax.swing.JRadioButton sexoM;
    // End of variables declaration//GEN-END:variables
}
